### ISSUE TITLE
PKCE support for public clients

### ISSUE THREAD

**Issue by srenatus** [dexidp/dex#1114]
It's intended to remedy possible attacks against public clients. See [RFC7636: Proof Key for Code Exchange by OAuth Public Clients](https://tools.ietf.org/html/rfc7636). It's a small twist to the authorization code flow:

```
                                                 +-------------------+
                                                 |   Authz Server    |
       +--------+                                | +---------------+ |
       |        |--(A)- Authorization Request ---->|               | |
       |        |       + t(code_verifier), t_m  | | Authorization | |
       |        |                                | |    Endpoint   | |
       |        |<-(B)---- Authorization Code -----|               | |
       |        |                                | +---------------+ |
       | Client |                                |                   |
       |        |                                | +---------------+ |
       |        |--(C)-- Access Token Request ---->|               | |
       |        |          + code_verifier       | |    Token      | |
       |        |                                | |   Endpoint    | |
       |        |<-(D)------ Access Token ---------|               | |
       +--------+                                | +---------------+ |
                                                 +-------------------+

                     Figure 2: Abstract Protocol Flow
```

Anyone interested in supporting this? 😃

**Comment by RichardLindhout** [comment]
Recommended for public clients according to this article: https://www.ory.sh/oauth2-for-mobile-app-spa-browser/

Myself are a bit sceptic about that because most companies would not like to open a webpage via the app itself.

**Comment by Teeed** [comment]
Adding link to pull request here: https://github.com/dexidp/dex/pull/1407

**Comment by tacurran** [comment]
@RichardLindhout would you open an issue in ory/hydra with an alternative flow to "open a webpage via the app". We would consider some other approach compatible with your point above.

**Comment by RichardLindhout** [comment]
Hey @tacurran, I'm not sure I think Hydra can handle this since you can build your own authorization logic e.g. username, password login for your own app while letting third parties do the login via the webpage.

However I think that's by definition something which could be handled by public clients since they are internal. I will make an issue because it can be an interesting discussion.

Would be nice if Hydra could handle these things more 'out of the box' but I'm not really sure.

(Hydra is really amazing I tried it 2 years ago I think but I think the documentation was not big enough because I could not get things to work)

By far the best approach best approach to oAuth I think!

**Comment by RichardLindhout** [comment]
Issue -> https://github.com/ory/hydra/issues/1938
