### ISSUE TITLE
Does dex plan to support session management ?

### ISSUE THREAD

**Issue by billgo** [dexidp/dex#1130]
Does dex plan to support session management ?
Or have any idea to do the logout ?

**Comment by ericchiang** [comment]
We may add some sort of automatic login based on an HTTP cookie for backends that support it, but these efforts will be transparent to apps that use dex. Dex remains un-opinionated about what you do with the user's identity once they're logged in. I don't see us adding features that apps can directly use because of that.

"Session management" can mean a lot of things though. Is there something concrete you're requesting?

**Comment by billgo** [comment]
https://openid.net/specs/openid-connect-session-1_0.html 
about this.
