### ISSUE TITLE
Can non-oauth2 service providers use dex as a SSO?

### ISSUE THREAD

**Issue by CodyKochmann** [dexidp/dex#1250]
I've been looking through the documentation and am curious if the service providers that are using dex are limited to only using oauth2 to talk to dex? 

Its a solid choice if thats the only one they can use. The issue is more with already built apps cooking up their own "use saml to provide sso for users" or "plug in your ldap server here to provide sso". 

For programming from scratch, if it hasn't been done yet, oauth2 is one of the ideal easy ways to do it. But for mature projects like gitlab, mattermost and various vpns theyve all kind of cooked in one of the many that dex offers and never mention oauth. 

Am I just reading things wrong? Or can dex use its connectors to talk to service providers in saml / ldap / ect as well?

**Comment by srenatus** [comment]
To use Dex to provide LDAP/SAML/whatnot authentication for your app, your app needs to act as an *OpenID Connect* client to Dex. Luckily, it's not too difficult, and there's libraries for various languages, see here: http://openid.net/connect/ and http://openid.net/developers/libraries/

> But for mature projects like gitlab, mattermost and various vpns theyve all kind of cooked in one of the many that dex offers and never mention oauth.

And I think that's a bummer! It would make so much sense to collaborate on getting this right instead of cooking your own. (To be fair, gitlab for example uses doorkeeper, so it's also not home-brewing this. An "extra service" approach like using Dex isn't a great fit for everyone.)

Looks like there's tiny bit of community engagement [here](https://mattermost.uservoice.com/forums/306457-general/suggestions/10197642-support-openid-connect) around OpenID Connect in Mattermost... If these _mature projects_ would just let you bring your own OIDC IdP, using Dex would be a good option to unify setup among multiple products 🤔

**Comment by srenatus** [comment]
I'm trying to clean up some stale issues. Please re-open if that answer wasn't satisfactory 😉
