### ISSUE TITLE
is project alive ?

### ISSUE THREAD

**Issue by freeseacher** [dexidp/dex#1276]
There are no commits since may nor pr-s merged. nothing. 
long holidays or i have to search alternatives ?

**Comment by srenatus** [comment]
@freeseacher I think this discussion is happening in #1273. Please ignore the issue's name, though, that only was what got the discussion started.

**Comment by ericchiang** [comment]
Just to add my two cents. At this point dex is maintained by volunteers, not engineers who are paid to work on it and that's been a rough transition.

@rithujohn191 has done a lot of work to move dex to its own org to grow its community outside of CoreOS/Red Hat.

@srenatus has volunteered to help out https://github.com/dexidp/dex/issues/1281 and we're exploring options to add more owners https://github.com/dexidp/dex/issues/1281

So that's where we're at. Please feel free to help out around the repo and we'll try to do our best to facilitate new contributions.

Closing for now. Dex could be lively, but we've managed to find contributors who are trying to improve that.
