### ISSUE TITLE
Disable CRD management

### ISSUE THREAD

**Issue by ernoaapa** [dexidp/dex#1308]
Hi,
we want to manage the CRDs by our self. What do you think of having `--disable-crd-creation` flag? Now if I create the CRDs and don't give RBAC to create customresourcedefinitions, I get a lot of spam to the logs. I can provide PR for this.

**Comment by srenatus** [comment]
I have to admit that I know little about this. Do other CRD-using services provide similar knobs?

**Comment by ericchiang** [comment]
I think others do. This should actually be a easy fix. Add an option here: https://github.com/dexidp/dex/blob/a1b6ba9bbad8bafbd680931a2bd5b6176df27dbb/storage/kubernetes/storage.go#L39

Then skip the create call later on.

**Comment by SongGithub** [comment]
hi @ernoaapa, this issue was addressed in PR #1333 by me, would you like to close this one?

I happened to have similar issue to yours that our team doesn't like to give DEX a clusterRole to create CRDs, providing this DEX instance is running from a client team namespace, and we have a DEX setup already in kube-system namespace with ClusterRole who has created required CRD types in all namespaces.

**Comment by ernoaapa** [comment]
Yeah, this can be closed. The #1333 solves my issue.
