### ISSUE TITLE
How to handle encrypted assertion in SAML authnResponse

### ISSUE THREAD

**Issue by houz42** [dexidp/dex#1404]
My internal IDP's authn response has only encrypted assertion. The saml connector does not handle it. Is there any way to tell my IDP to response unencrypted assertion with signature in my SP metadata or authn request?

By the way, I found some golang saml implementation supports more saml functionalities, including encrypted assertion, multiple assertions, and medata rotation. https://github.com/crewjam/saml for example. Do we consider use a 3rd party saml implementation?

**Comment by ericchiang** [comment]
We don't support encrypted assertions.

We've already had serious security issues with SAML, and the security industry as a whole generally agrees that it's not a good protocol. I'd prefer to see users move to more sane authentication mechanisms like OAuth2 based flows instead of expanding our SAML support or taking in new SAML code.

**Comment by houz42** [comment]
Thanks for your reply, I may try other protocols.

**Comment by houz42** [comment]
By the way, how about document the above suggestion for other users?
