### ISSUE TITLE
Refresh id_token?

### ISSUE THREAD

**Issue by jwomble** [dexidp/dex#1646]
I've got dex setup and am using an implicit flow to login to a website.  Is there a way to refresh/renew a user's id_token before it expires?  I need to set my token expiration time to 15 minutes, and I'd rather not log the user out if they are in the middle of something.

Thanks!

**Comment by nabokihms** [comment]
Yes, you can use the refresh token grant to periodically refresh the token.
https://oauth.net/2/grant-types/refresh-token/

To solve the problem when user is logged out in the middle of something, you can refresh tokens on the background or earlier, e.g., after 7 minutes of 15.

P.S. I'm not sure whether this issue is still relevant, but answer is an answer 😅 I'm going toclose this one. Feel free to reopen it if you still have questions to answer.
