### ISSUE TITLE
Need to expose JWT signing keys for automation

### ISSUE THREAD

**Issue by cydonknight** [dexidp/dex#1826]
Hello!

I am currently working on a Dex implementation and for cicd/automation purposes need to be able to generate my own JWT either via Dex or using the Dex signing key. Is there a way to instruct Dex to provide a JWT with a given set of inputs, independent of any provider/connector/login action?

I've gone as far as attempting to parse the signing keys via a connected postgres backend (to create my own JWTs) but it looks like the key itself is encoded. Is this a viable route to pulling the signing key?

I'm aware of the static key mode recently implemented, however it's not currently functional as there is no way to start the server with a key via the cmd options.

Any help would be appreciated.

Thanks!

**Comment by nabokihms** [comment]
It doesn't seem right to sign tokens with Dex keys. You can only receive a token by authenticating, and there are many ways how you can do this.

For CI/CD automation, we have the new feature name token exchange. See for more details
https://github.com/dexidp/dex/blob/master/docs/enhancements/token-exchange-2023-02-03-%232812.md

I'm going to close this issue due to its age. If you still have a problem, please consider opening a new one. Thanks!
