### ISSUE TITLE
Allow public clients created as staticClients to have no client_secret

### ISSUE THREAD

**Issue by AmandeepBhupal** [dexidp/dex#1894]
#### Expected behavior (what you expected to happen)
The expected behaviour is to not get any error when no client secret is given because I am trying to enable pkce flow with a public client.

#### Actual behavior (what actually happened)
I actually receive an error: 
Invalid config: Secret or secretEnv field is required for client ""

#### Steps to reproduce

1. In staticClient, set public: true, give clientID, name, redirectURL, but no client , or just even with client: ""

#### Environment

- Dex version: dex helm charts
- Storage type: in-cluster
- Installation type (official docker image, helm chart, etc.): Helm chart

#### Additional information for debugging (if necessary)

Any tips on how do I enable Dex server to work with PKCE flow.

**Comment by heidemn** [comment]
@AmandeepBhupal this should already work since https://github.com/dexidp/dex/pull/1822 / [v2.26.0](https://github.com/dexidp/dex/milestone/18) .

Is it possible that your Helm Chart uses an outdated version of Dex?

**Comment by AmandeepBhupal** [comment]
Hii @heidemn 
Thanks for your reply to the issue. I am using the official fork as directed here: https://github.com/elastisys/compliantkubernetes-apps/issues/75
According to comment from @sagikazarmark it seems like the official maintained fork. Please suggest what should I be using this one itself, or the one you're suggesting.

Also, I got the error from Dex. The image being used is: banzaicloud/dex-shim

Thanks so much!

**Comment by heidemn** [comment]
@AmandeepBhupal probably you can update the dex-shim version by passing `imageTag: "0.7.0"` to the chart.
That version seems to ship the latest Dex release v2.27.0.
PKCE is supported since Dex [v2.26.0](https://github.com/dexidp/dex/releases/tag/v2.26.0), so your described configuration should work then.

The current default  in [values.yaml](https://github.com/banzaicloud/banzai-charts/blob/master/dex/values.yaml#L7) is `imageTag: "0.6.0"`, which results in the old Dex version v2.23.0, see below.

```
$ docker run -ti --rm banzaicloud/dex-shim:0.6.0 version
dex Version: v2.23.0
Go Version: go1.13.8
Go OS/ARCH: linux amd64

$ docker run -ti --rm banzaicloud/dex-shim:0.7.0 version
dex Version: v2.27.0-dirty
Go Version: go1.15.6
Go OS/ARCH: linux amd64
```

**Comment by AmandeepBhupal** [comment]
Perfect! Thank you so much!!
