### ISSUE TITLE
Add MySQL support for storage

### ISSUE THREAD

**Issue by ericdai** [dexidp/dex#200]
we are a mysql and  ms sql server based company ,we did not use postgresql.
so I want to know if there is  any plan to support mysql and MSSQL server?

**Comment by ericchiang** [comment]
Adding additional backends isn't in the immediate roadmap. But, because dex uses [gorp](https://github.com/go-gorp/gorp) to construct queries and [sql-migrate](https://github.com/rubenv/sql-migrate) for migrations, other SQL flavors _should_ work.

If you'd like to test MySQL or MSSQL server, I'm sure others would appreciate it!

To test other drivers, you'd need to alter:
1. The database connection code [here](https://github.com/coreos/dex/blob/2a1d32e6e8e983cebdb50999ddd5c2cc73a945e8/db/conn.go#L45)
2. The migration dialect [here](https://github.com/coreos/dex/blob/2a1d32e6e8e983cebdb50999ddd5c2cc73a945e8/db/migrate.go#L14)

**Comment by bobbyrullo** [comment]
I am pretty sure there are postgres specific features in there - some stuff
related to quoting in SQL statements comes to mind.

But yeah, like Eric said, supporting other backends is not a priority for
us over here.

**Comment by craigtracey** [comment]
This is a first (completely untested) pass at mysql support:
https://github.com/craigtracey/dex/tree/mysql-support

Early comments welcome.

**Comment by ericchiang** [comment]
Cool!

I'll go ahead and reopen this issue. Feel free to submit a PR if you'd like to run against travis, but I imagine there are some overall organizational changes to the code we're going to need to discuss.

**Comment by rudolfv** [comment]
@ericchiang It's been a while and was wondering what happened to this? Are you still open to PRs for adding MySQL support for storage?

**Comment by srenatus** [comment]
#1485 ✅
