### ISSUE TITLE
exec format error starting with v2.28 on arm64

### ISSUE THREAD

**Issue by rust84** [dexidp/dex#2052]
#### Expected behavior (what you expected to happen)

Since https://github.com/dexidp/dex/pull/1781 added arm64 support I have been running Dex successfully in k3s on a raspberry pi cluster running Ubuntu server 64bit. This was working perfectly in v2.27.0 however since upgrading to v2.28.0 the pod is unable to start on arm nodes.

#### Actual behavior (what actually happened)

The pod exits with the following error message.

standard_init_linux.go:219: exec user process caused: exec format error                                                                                       stream closed 

#### Steps to reproduce

1. Create a k3s v1.19.8 cluster on raspberry pi.
2. Deploy Dev v2.28 using helm
3. Wait for pod to start and check for error

#### Environment

- Dex version: v2.28
- Storage type: 
- Installation type (official docker image, helm chart, etc.):  ghcr.io/dexidp/dex:v2.28.0

**Comment by sagikazarmark** [comment]
Looks like the slim version of gomplate doesn't work properly on arm: hairyhenderson/gomplate#1085

**Comment by sagikazarmark** [comment]
@rust84 please try v2.28.1

**Comment by rust84** [comment]
@sagikazarmark I've tried v2.28.1 and unfortunately am still getting the same error.

**Comment by sagikazarmark** [comment]
@rust84 can you provide some more details about your environment? I tried it on Graviton and RPI 4 and it works on both.

**Comment by rust84** [comment]
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan
$ uname -r
5.3.0-1030-raspi2
```

Yes I need to upgrade these 😄

**Comment by sagikazarmark** [comment]
@rust84 Feels like the fix is not actually related to your original problem. The error message suggests that the image/binary is not for that particular architecture (which was actually the case with gomplate, but that yielded a different error message).

Can you please try upgrading to a newer version to see if you get the error there too?

I didn't add k3s to the mix, can you try using Docker directly to see if the problem is there? (I very much doubt it, but it's easy to test: as of 2.28.0 you should be able to launch a Dex container without any configuration)

**Comment by rust84** [comment]
I'll update the OS and get back to you. Thanks for your help.

**Comment by rust84** [comment]
Sorry for the delay. I can confirm that upgrading to 20.04 has resolved the issue.
