### ISSUE TITLE
quay.io organization ongoing access

### ISSUE THREAD

**Issue by ericchiang** [dexidp/dex#2070]
Hey everyone,

I'm one of the owners of the quay.io/dexidp/dex image, and with Red Hat requiring registering a Red Hat account to access quay, I plan on letting that account lapse.

https://access.redhat.com/articles/5363231

Just wanted to give a heads up and see if anyone wanted access to it. Since dex has switched to an alternative container provider I'm assuming this won't be a future issue, but I don't know the implications if someone decides to re-register the dexidp organization. E.g. if they'd be able to server malicious images for anyone still pulling quay.io/dexidp.dex

Eric

**Comment by sagikazarmark** [comment]
Hi @ericchiang,

Yeah, we don't use quay anymore for distributing "official" Dex images. The only reason why I would keep it though is because the [old helm chart](https://github.com/helm/charts/blob/master/stable/dex/values.yaml#L6) still points to quay.

Can you add me as an admin to the organization? My username is `sagikazarmark`.

Thanks!

**Comment by ericchiang** [comment]
Sweet, I sent you an invite to https://quay.io/organization/dexidp!

Going to call this fixed. Let me know if there's anything else I can do :)

**Comment by sagikazarmark** [comment]
Awesome, thanks!

**Comment by sagikazarmark** [comment]
I disabled the build trigger, so from this point we won't be building Dex on quay automatically.
