### ISSUE TITLE
readinessProbe is not https scheme

### ISSUE THREAD

**Issue by wangyanghack** [dexidp/dex#2076]
#### Expected behavior (what you expected to happen)
Run dex.yaml successfully

#### Actual behavior (what actually happened)
readinessProbe in dex pod is not success.
#### Steps to reproduce

1. ...
2. ...
3. ...

#### Environment

- Dex version:
- Storage type:
- Installation type (official docker image, helm chart, etc.):

#### Anything else we should know?
As result, I add **Scheme: HTTPS** to readinessProbe, dex pod can run successfully. 
I think the reason is config in dex is https in default. dex cannot ping http://127.0.0.1:5556/healthz in readinessProbe because dex is serve https  in default.
So i think if we should switch http to https by add **Scheme: HTTPS** to readinessProbe to resolve the problem.

#### Additional information for debugging (if necessary)

<details><summary>Configuration</summary><br><pre>

</pre></details>

<details><summary>Logs</summary><br><pre>

</pre></details>

**Comment by sagikazarmark** [comment]
This is already fixed in the latest Dex version and in the latest Helm chart: the health check uses a different (telemetry) server that is always HTTP. 

https://github.com/dexidp/helm-charts/blob/master/charts/dex/templates/deployment.yaml#L79-L86

I suspect you use an old Dex version and/or an old Helm chart/Kubernetes manifest. Please upgrade Dex and use the new Helm chart.

**Comment by wangyanghack** [comment]
I use example in master branch Dex.
[https://github.com/dexidp/dex/blob/b79d9a84bc0c35e13a9d5141e95b641af0f81c8f/examples/k8s/dex.yaml#L79-L82](url)
[https://github.com/dexidp/dex/blob/b79d9a84bc0c35e13a9d5141e95b641af0f81c8f/examples/k8s/dex.yaml#L52-L55](url)
please check it, thanks.
