### ISSUE TITLE
separate config for issuerURL and issuerPath

### ISSUE THREAD

**Issue by facundo-tul** [dexidp/dex#2097]
we are using ambassador to put dex in a sub path `example.com/dex/ ` the issuer config is set to `example.com/dex/` this makes the internal path to change to `/dex/` as it is explained in the documentation

```The base path of dex and the external name of the OpenID Connect service.
This is the canonical URL that all clients MUST use to refer to dex. If a
path is provided, dex's HTTP service will listen at a non-root URL.
```
this issue makes my dex + ambassador to make the url `example.com/dex/dex/`
this is my partial value for the helm chart:

```service:
  ports:
    http:
      port: 80
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: ambassador
  hosts:
    - host: example.com
      paths:
        - path: /dex/    
config:
  issuer: https://example.com/dex/```
there is a way to separate this behavior?

**Comment by nabokihms** [comment]
It looks like there is a problem with the ambassador configuration. I think there is something that allows you to rewrite the path https://www.getambassador.io/docs/edge-stack/latest/topics/using/rewrites/ 

I am not an experienced ambassador user, nor an ordinary user either. Thus I could not suggest you more.

Closing the issue because it doesn't look like it is connected to dex.
