### ISSUE TITLE
Add options for writing logs to the file

### ISSUE THREAD

**Issue by rudeigerc** [dexidp/dex#2220]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.

### Problem Description

Currently, the logger writes the output to `os.Stderr` by default.

```go
func newLogger(level string, format string) (log.Logger, error) {
	...
	return &logrus.Logger{
		Out:       os.Stderr,
		Formatter: &formatter,
		Level:     logLevel,
	}, nil
}
```

Since under our circumstances we have to collect logs from the specified path, it would be better to have an option to allow files to be the output target.

### Proposed Solution

Provide an option to allow writing logs to the file.

### Additional Information

I would be glad to submit a PR if the request was accepted :)

**Comment by sagikazarmark** [comment]
Hi @rudeigerc !

Can you please elaborate your use case and explain why forwarding logs from stderr work for you? IMHO it's an established practice to log to stderr and forward logs to files if necessary.

Personally, I'm not a huge fan of log files as they can do more harm, so I'd like to understand and examine every detail carefully before adding something like this to Dex. Right now, I'm more in favor of leaving this to other tools.

**Comment by rudeigerc** [comment]
Hi @sagikazarmark! Thanks for your reply. We deploy Dex on Kubernetes as an identity service connecting our own identity provider with a custom connector, and we collect logs from the specified mounted host path in our practice. The collector would collect logs from this host path on the nodes periodically. As a result, we have to follow this design to adapt to our infrastructure.

**Comment by sagikazarmark** [comment]
Well, I'm going to assume you know that logs sent to container stdout/stderr _are_ written to files on the host.

I don't really like the idea to build this into Dex. I believe you could easily run the image with a custom command that tails the output of `dex serve` and writes it to a file of your liking. It's much more elegant than adding it to Dex directly and it doesn't even require a custom image.

If you allow me a personal comment: It's pretty much standard practice to let the container engine collect the logs from stdout/stderr, write them to files on the host that you can easily pick up and forward to your preferred log storage/log analysis tool. I'm not sure how your infrastructure works, but based on your descriptions you are doing something slightly different.

I'm gonna close this issue as won't fix, because I think it can be solved without changes in Dex, but even if it weren't true, the use case is too specific to your infra which doesn't seem to follow Kubernetes practices.
